Sikap/Sikap/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/',include('login.urls')),
    path('register/',include('register.urls')),
    path('',include('landing.urls')),
    path('view/',include('viewas.urls')),
    path('posts/',include('posts.urls')),
]

Sikap/landing/urls.py
from django.urls import path
from . import views

app_name = 'landing'
urlpatterns = [
    path('',views.LandingView.as_view(),name="landing_view"),
    # path('dashboard/',views.DashboardView.as_view(),name="dashboard_view"),
    # path('products/',views.ProductView.as_view(),name="products_view"),
    # path('regproducts/',views.RegisterProductView.as_view(),name="reg_products_view"),
    # path('customers/',views.CustomerView.as_view(),name="customers_view"),
    # path('regcustomers/',views.RegisterCustomerView.as_view(),name="reg_customers_view"),
    # path('demo/',views.DemoView.as_view(),name="demo_view"),
    # path('buy/',views.DemobView.as_view(),name="demob_view"),
    # path('end/',views.EndView.as_view(),name="end_view"),
]

Sikap/login/urls.py
from django.urls import path
from . import views

app_name = 'login'
urlpatterns = [
    path('',views.LoginView.as_view(),name="login_view"),
    # path('dashboard/',views.DashboardView.as_view(),name="dashboard_view"),
    # path('products/',views.ProductView.as_view(),name="products_view"),
    # path('regproducts/',views.RegisterProductView.as_view(),name="reg_products_view"),
    # path('customers/',views.CustomerView.as_view(),name="customers_view"),
    # path('regcustomers/',views.RegisterCustomerView.as_view(),name="reg_customers_view"),
    # path('demo/',views.DemoView.as_view(),name="demo_view"),
    # path('buy/',views.DemobView.as_view(),name="demob_view"),
    # path('end/',views.EndView.as_view(),name="end_view"),
]

Sikap/register/urls.py
from django.urls import path
from . import views

app_name = 'register'
urlpatterns = [
    path('',views.RegisterView.as_view(),name="register_view"),
    # path('dashboard/',views.DashboardView.as_view(),name="dashboard_view"),
    # path('products/',views.ProductView.as_view(),name="products_view"),
    # path('regproducts/',views.RegisterProductView.as_view(),name="reg_products_view"),
    # path('customers/',views.CustomerView.as_view(),name="customers_view"),
    # path('regcustomers/',views.RegisterCustomerView.as_view(),name="reg_customers_view"),
    # path('demo/',views.DemoView.as_view(),name="demo_view"),
    # path('buy/',views.DemobView.as_view(),name="demob_view"),
    # path('end/',views.EndView.as_view(),name="end_view"),
]

Sikap/landing/models.py
from django.db import models

# Create your models here.

Sikap/landing/views.py
from django.shortcuts import render,redirect
from django.views.generic import View,TemplateView
from django.http import HttpResponse
from .models import *
#from .forms import *
# Create your views here.
class LandingView(View):
    def get(self,request):
        return render(request,'index.html')

Sikap/landing/templates/index.html
<html>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

<style>
    body {
    
    
    background-color: #FFFFFF;
    height: 100vh;
    color: black;
}
    nav {
        color: white;
    }

aside {
    width: 30%;
    padding-left: 15px;
    margin-left: 15px;
    float: right;
    font-style: italic;
    background-color: lightgray;
}
    
.tat{
    position: fixed;
}

.fill{
    height: 10%;
}

.navbar{    
    width: 100%;
    position:fixed;
    background: whitesmoke;

}

.nav-right {
    float: right;
}
</style>

<body>
    <nav class="navbar sticky-top navbar-light bg-dark">
        <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand" href="#">Sikap</a>
          </div>
            <ul class="nav navbar-nav">
                <li class="active"><a href="#">Home</a></li>
                <li class="text-secondary"><a href="#">Find Employers</a></li>
                <li class="text-secondary"><a href="#">Profile</a></li>
                <li><a href="#" class="text-secondary">Explore</a></li>
            </ul>
            <div class="nav-right">
                <form class="form-inline my-2 my-lg-0 al" style="padding-top: 10px;">                        
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" style="background: #0496ff;" type="submit">Search</button>
                </form>   
            </div>
        </div>
    </nav>

    
    <div class="fill"></div>
    <div class="container">
        <div style="background: #4bb3fd"class="jumbotron text-center color-primary">
            <h1>picture ni dinhi</h1>
            <p>YEEEET</p> 
      </div>
      LANDING
    <button><a href="{% url 'login:login_view' %}">LOGIN</a></button>
    REGISTRATION
    <button><a href="{% url 'register:register_view' %}">REGISTER</a></button>
      <div>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacinia pulvinar dolor vitae tempor. 
        Etiam ac lorem non felis iaculis pellentesque sed a metus. Quisque sit amet nulla magna. Curabitur 
        a tellus vitae metus sodales ultrices. Curabitur volutpat magna vitae risus iaculis, eget malesuada 
        ex hendrerit. Vivamus tincidunt enim ut facilisis facilisis. Nam dignissim mattis viverra.

        Vestibulum vehicula felis et lorem tempor, ut eleifend leo vehicula. Mauris eu felis neque. Ut egestas, 
        ipsum ac pretium tincidunt, enim nisi volutpat orci, sed lobortis elit lectus a lorem. Phasellus at ipsum 
        eget purus efficitur iaculis eu id massa. Interdum et malesuada fames ac ante ipsum primis in 
        faucibus. Sed eget egestas nunc. Vestibulum ornare urna sed rhoncus maximus. Suspendisse iaculis rutrum
        hendrerit. Duis suscipit mattis laoreet. Cras sit amet interdum neque. Quisque consectetur nulla quis 
        augue ornare, vitae scelerisque nulla ultrices. Morbi sodales posuere justo, quis porttitor nisl varius 
        eget. Aenean ultricies pellentesque purus a mattis. Sed ut risus lacus. Vivamus lobortis tristique 
        elementum. Quisque sodales lorem justo, et luctus orci finibus sit amet.
        <br>
        Vestibulum vehicula felis et lorem tempor, ut eleifend leo vehicula. Mauris eu felis neque. Ut egestas, 
        ipsum ac pretium tincidunt, enim nisi volutpat orci, sed lobortis elit lectus a lorem. Phasellus at ipsum 
        eget purus efficitur iaculis eu id massa. Interdum et malesuada fames ac ante ipsum primis in 
        faucibus. Sed eget egestas nunc. Vestibulum ornare urna sed rhoncus maximus. Suspendisse iaculis rutrum
        hendrerit. Duis suscipit mattis laoreet. Cras sit amet interdum neque. Quisque consectetur nulla quis 
        augue ornare, vitae scelerisque nulla ultrices. Morbi sodales posuere justo, quis porttitor nisl varius 
        eget. Aenean ultricies pellentesque purus a mattis. Sed ut risus lacus. Vivamus lobortis tristique 
        elementum. Quisque sodales lorem justo, et luctus orci finibus sit amet.
        <br>
        <aside style="background: #04487c; color:white";>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus lacinia pulvinar dolor vitae 
            tempor. Etiam ac lorem non felis iaculis pellentesque sed a metus. Quisque sit amet nulla magna. 
            Curabitur a tellus vitae metus sodales ultrices. Curabitur volutpat magna vitae risus iaculis, 
            eget malesuada ex hendrerit. Vivamus tincidunt enim ut facilisis facilisis. Nam dignissim mattis 
            viverra.
        </aside>
        Vestibulum interdum metus eros, fermentum convallis dolor dignissim id. Cras porttitor diam ac interdum 
        pretium. Donec tincidunt vestibulum mi. Vivamus faucibus neque quis risus maximus, vitae commodo felis 
        congue. Nulla bibendum mauris sit amet eros pretium laoreet. Integer non nisi nulla. Nam ullamcorper ex 
        vitae ultricies ullamcorper. Donec quis dolor eleifend, tempus nisi nec, viverra ante. Nam gravida 
        luctus nunc ac rutrum. Nunc in consectetur massa. Quisque ornare blandit diam id efficitur.
        <br>
        Vivamus eros leo, lobortis vel interdum non, imperdiet ut justo. Nulla at congue nibh. Ut dictum 
        luctus orci at maximus. Suspendisse elementum egestas metus. Phasellus non tellus a urna venenatis 
        sagittis. Phasellus eget lorem ornare, cursus ipsum sed, facilisis eros. Mauris ut vehicula est. 
        Proin dignissim diam in ipsum consectetur vehicula. Mauris vel faucibus neque. Lorem ipsum dolor 
        sit amet, consectetur adipiscing elit. Vivamus maximus massa nec feugiat pretium.
      </div>
    </div>
</body>
</html>

Sikap/landing/templates/landing.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>LANDING</title>
</head>
<body>
    LANDING
    <button><a href="http://127.0.0.1:8000/login">LOGIN</a></button>
</body>
</html>